### ISSUE TITLE
Move CSS and JS into separate files

### ISSUE THREAD

**Issue by CappeSun** [CappeSun/Issue-practice#2]
Simply move what's inside the style and script tags in index.html into their own files, and link to those in index.html.

**Comment by tharikashree** [comment]
Hey can i work on this?

**Comment by CappeSun** [comment]
You're very welcome to! :)

**Comment by Nandini1071** [comment]
is this still open, if yes would like to contribute on this ? @CappeSun

**Comment by CappeSun** [comment]
@Nandini1071 Sorry, just closed

**Comment by Nandini1071** [comment]
Okay no issues, let me know if any changes or coding required would like to contribute?
